### ISSUE TITLE
How To Configure Purger?

### ISSUE THREAD

**Issue by Carmezim** [cortexproject/cortex-helm-chart#145]
https://cortexmetrics.io/docs/configuration/configuration-file/#purger_config

**Comment by Carmezim** [comment]
Needs to be set on querier, query-frontend, table-manager and ruler service, for now with extraArgs (flags)

**Comment by danfromtitan** [comment]
Did you get purger to work this way by deleting tenants or time series ? I can't get any of the [purger API calls to work](https://cortexmetrics.io/docs/api/#purger), I keep getting _404 page not found_

curl -H "X-Scope-OrgID: test" http://cortex-querier.cortex.svc.cluster.local:8080/purger/delete_tenant_status
404 page not found

It also puzzles me why purger would be enabled in querier or query-frontend, I would expect it rather in the compactor since that's the one responsible for storage blocks maintainance.

**Comment by bilbof** [comment]
Unfortunately this won't work if you're using block storage (chunk storage is deprecated) which doesn't yet support deleting time series: https://github.com/cortexproject/cortex/issues/4267 https://github.com/cortexproject/cortex/pull/4370

If you're using chunk storage, if you're running in distributed mode you'll need to run an additional purger service (i.e. `-target=purger`) which isn't supported by this helm chart, just pull an existing deployment from cortex and modify it `k get deployment cortex-querier -oyaml > purger.yaml; vi purger.yaml; k apply -f purger.yaml`
