### ISSUE TITLE
data mount for ingester and store-gateway should match cortex config defaults

### ISSUE THREAD

**Issue by justinrush** [cortexproject/cortex-helm-chart#223]
The [default data directory](https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config) for the bucket store and tsb is /tsdb. The helm chart should default to that directory rather than /data.

I realize this can be "worked around" by adding to the config element, but that isn't intuitive. This chart is for deploying cortex and thus it should have sane defaults.

"work around" issue: https://github.com/cortexproject/cortex-helm-chart/issues/74

**Comment by ShuzZzle** [comment]
> The helm chart should default to that directory rather than /data.
Yes that is because that is where the volume is mounted so everything is mounted within /data. Also the root file system is protected for safety reasons.

> I realize this can be "worked around" by adding to the config element, but that isn't intuitive.
Agree. We can add defaults to the values.yaml

**Comment by justinrush** [comment]
I'm confused - the only thing that uses that data directory is the blocks_storage, whose default value in cortex is /tsdb. Why mount this in /data?

Maybe I'm misunderstanding how to use the helm chart, but my understanding is I need to provide a value for the root `config` key, so you aren't going to be able to change the cortex default from /tsdb to /data, since any default you put in `config` has to be overridden by whomever deploys the chart.

If the chart is supposed to be building `config` for me, then I'm just doing it wrong and would love to know that :)

**Comment by ShuzZzle** [comment]
> I'm confused - the only thing that uses that data directory is the blocks_storage, whose default value in cortex is /tsdb. Why mount this in /data?

The kubernetes **persistent volume** is mounted at **/data** because the root-file system is read-only due to security best-practices. We could mount it at /tsdb but that is not the only usage as I for example also have different sub folders for **tsdb** and **tsdb-sync**

```yaml
    tsdb:
      dir: "/data/tsdb"
    bucket_store:
      sync_dir: "/data/tsdb-sync"
```
or
```yaml
    lifecycler:
      # Token file
      tokens_file_path: "/data/tokens"
```
> Maybe I'm misunderstanding how to use the helm chart, but my understanding is I need to provide a value for the root `config` key, so you aren't going to be able to change the cortex default from /tsdb to /data, since any default you put in `config` has to be overridden by whomever deploys the chart.

> If the chart is supposed to be building `config` for me, then I'm just doing it wrong and would love to know that :)

I don't quite understand what you mean, but here is how can we can improve the experience for the operator. With release of version 1.0.0 we will most likely switch from default chunk storage to block storage. By doing that we can set better defaults (like the above) which results in people like you and me having less pain in configuring cortex.

You can see a sample of how a cortex minimal configuration looks like [here](https://github.com/cortexproject/cortex-helm-chart/blob/master/ci/test-values.yaml) or [here](https://cortexproject.github.io/cortex-helm-chart/guides/getting_started_with_block_storage.html)

By the way the cortex defaults are not always the best idea or applicable in a kubernetes environment

**Comment by justinrush** [comment]
Those test CI values were SUPER helpful - thanks!  Linking near the top of the README in the v1 release will likely be helpful for others as well.

I don't know what other environment you'd actually run Cortex in other than Kubernetes, but point taken, your explanation makes sense to me.
