### ISSUE TITLE
Ingester PVC clean up after scale down

### ISSUE THREAD

**Issue by mweibel** [cortexproject/cortex-helm-chart#495]
I noticed recently that cortex ingester PVCs stay in the cluster after scaling down (we deploy ingester as a StatefulSet).

If I understand [the docs](https://cortexmetrics.io/docs/guides/ingesters-scaling-up-and-down/) correctly, it should be relatively safe to clean up the PVCs when having the preStop shutdown call set up for ingesters. 

Are there any recipes you use to clean those up?

[STS PersistentVolumeClaim retentionPolicy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention) might be an idea but it's feature flagged and therefore not possible to activate in our case (managed cluster).

**Comment by nschad** [comment]
Sorry for the late reply.

> If I understand [the docs](https://cortexmetrics.io/docs/guides/ingesters-scaling-up-and-down/) correctly, it should be relatively safe to clean up the PVCs when having the preStop shutdown call set up for ingesters.

Yes the problem is that you have to hit the `/ingester/shutdown` endpoint before the Pod is restarted or killed by force so a very long termination grace period is key here. When using a STS it also can be beneficial to "orphan" the pods so that they don't get automatically recreated. In either case scale-down have to be done manually.

> Are there any recipes you use to clean those up?

As mentioned earlier I actually do not have the preStop lifecycle setup as it interfere with "normal" restarts. So basically I delete the statefulset with `--cascade=orphan` and then shutdown one ingester by one. After that you can simply recreate the STS with a smaller replica.

**Comment by mweibel** [comment]
No worries - I was off anyway :smile: 

Thanks for the explanation.
We use a HorizontalPodAutoscaler for the ingester due to the spiky nature of the workload we deploy. In the usual case we have 3 ingesters running but it scales up or down based on the used memory of the ingester. 
From there also the question stems - since we scale up/down automatically, the PVC clean up doesn't happen. But I assume the issue we could have there is not all metrics being flushed before the ingester is taken down and the 240s grace period we have might not be enough. 

Not sure how others do that with Cortex.

**Comment by nschad** [comment]
> No worries - I was off anyway 😄
> 
> Thanks for the explanation. We use a HorizontalPodAutoscaler for the ingester due to the spiky nature of the workload we deploy. In the usual case we have 3 ingesters running but it scales up or down based on the used memory of the ingester. From there also the question stems - since we scale up/down automatically, the PVC clean up doesn't happen. But I assume the issue we could have there is not all metrics being flushed before the ingester is taken down and the 240s grace period we have might not be enough.
> 
> Not sure how others do that with Cortex.

Usually it is not recommended to scale-down automatically with HPA. That's why it is not enabled per-default here. But yeah my guess is that the 240s are definitely not enough. And yes you guys could use the PVC ScaleDown delete thingy for clean-up. Although it shouldn't be that bad as the disk should be empty anyway after correct flush or atleast it will be eventually.

**Comment by mweibel** [comment]
Ok. Thank you for the information 👍 Will investigate more about this.
